### ISSUE TITLE
New Sources [ Please 🥺❤️ ]

### ISSUE THREAD

**Issue by OshekharO** [Moleys/vbook-ext#4]
English:
https://mtlnation.com/
https://novelsemperor.com/
https://reaperscans.com/
https://www.mtlnovel.com/
https://comrademao.com/
https://asura.gg/
https://ranobes.net/

Chinese:
https://www.ffxs8.com/
https://www.sjks8.cc/
https://www.jpxs123.com/
https://m.bixiange.me/
https://m.feixs.com/

Japanese:
https://kakuyomu.jp/
https://syosetu.org/
https://yomou.syosetu.com/

**Comment by Moleys** [comment]
Available:

-Chinese:
https://www.ffxs8.com/
https://www.jpxs123.com/
https://m.bixiange.me/
https://www.sjks8.cc/ (it's http://www.sjks88.com/)

-Japanese:
https://kakuyomu.jp/
https://yomou.syosetu.com/
For Japanese, You need to add this Repo:
https://raw.githubusercontent.com/khoa301020/vbook-ext/master/plugin.json
Tutorial: 
*All extension* => *Repository manager* => paste the above link

Websites I won't create: 
https://mtlnation.com/ 
https://novelsemperor.com/ 
Due to Cloudflare Checking

**Comment by OshekharO** [comment]
Okk thanks for your reply
